'use client'
import {useEffect,useState} from 'react'
import {Bot,Send,Sparkles,FileSearch,Calculator,Users,ReceiptText,X} from 'lucide-react'

const starters=[
 {icon:FileSearch,label:'Review plans',intent:'quotes',prompt:'Review the available project information and prepare a takeoff. Flag every missing measurement or specification.'},
 {icon:Calculator,label:'Draft quote',intent:'quotes',prompt:'Prepare a draft quotation using approved current prices only. Show historical evidence separately and list missing commercial inputs.'},
 {icon:Users,label:'Find leads',intent:'leads',prompt:'Review our lead pipeline and commercial context and tell me the best next Palawan opportunities and next actions.'},
 {icon:ReceiptText,label:'Billing',intent:'invoices',prompt:'Show approved jobs ready for draft billing, unpaid balances, and anything blocking invoice preparation.'}
]
export default function AgentPanel({open,onClose}){
 const [messages,setMessages]=useState([{role:'agent',text:'I’m ready. Give me plans, measurements, a customer request, or ask about leads, quotes, invoices or commercial memory.'}])
 const [input,setInput]=useState(''),[models,setModels]=useState([]),[model,setModel]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{if(!open||models.length)return;fetch('/api/agent/models').then(r=>r.json()).then(d=>{setModels(d.models||[]);if(d.models?.length)setModel(d.models[0].id);if(d.error)setError(d.error)}).catch(()=>setError('Could not load OpenRouter free models.'))},[open,models.length])
 const send=async(text=input,intent='general')=>{if(!text.trim()||busy)return;if(!model){setError('Select a free OpenRouter model first.');return}setMessages(m=>[...m,{role:'user',text}]);setInput('');setBusy(true);setError('');try{const r=await fetch('/api/agent',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,model,intent})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Agent request failed');setMessages(m=>[...m,{role:'agent',text:d.reply||'No response returned.'}])}catch(e){setError(e.message)}finally{setBusy(false)}}
 if(!open)return null
 return <aside className="agent-panel"><div className="agent-head"><div className="agent-avatar"><Bot size={19}/></div><div><strong>Azarraga Agent</strong><span><i/> Commercial memory connected</span></div><button onClick={onClose}><X size={18}/></button></div><div className="agent-context"><Sparkles size={15}/><span>Find business · Quote jobs · Manage billing</span></div><div style={{padding:'0 16px 12px'}}><label style={{fontSize:11,fontWeight:700,display:'block',marginBottom:6}}>OPENROUTER FREE MODEL</label><select value={model} onChange={e=>setModel(e.target.value)} style={{width:'100%',padding:'10px',border:'1px solid #d8dee8',borderRadius:8,background:'#fff'}}><option value="">Select model</option>{models.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></div><div className="agent-starters">{starters.map(({icon:Icon,label,prompt,intent})=><button key={label} onClick={()=>send(prompt,intent)} disabled={busy}><Icon size={15}/><span>{label}</span></button>)}</div><div className="agent-messages">{messages.map((m,i)=><div key={i} className={`agent-message ${m.role}`}>{m.text}</div>)}{busy&&<div className="agent-message agent">Working with ICM…</div>}{error&&<div className="agent-message agent" style={{borderColor:'#b42318'}}>Error: {error}</div>}</div><div className="agent-compose"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Ask the Azarraga Agent…"/><button onClick={()=>send()} disabled={busy}><Send size={17}/></button></div><small className="agent-note">Free models are discovered live from OpenRouter. Agent prepares; deterministic engines calculate; Azarraga approves.</small></aside>
}
