'use client'
import {useMemo,useState} from 'react'
import {Search,FileText,ReceiptText,BrainCircuit,Plus,MapPin,Upload,Calculator,CheckCircle2,Building2,ArrowRight,Send} from 'lucide-react'

const products=['900 Series sliding','Pocket sliding','Frameless swing door','Shower enclosure','Jalousie / Jalouplus','Fixed glass','Awning / casement','Bi-fold','Slide-up','Mullion','Glass railing','Canopy','Storefront','ACP','Roll-up','Screen door','Tabletop / shelves','Aquarium']
const seedLeads=[{name:'New Resort Development',place:'El Nido',type:'Hospitality',stage:'Research',score:92},{name:'Villa Construction',place:'San Vicente',type:'Residential',stage:'Qualified',score:84},{name:'Commercial Renovation',place:'Puerto Princesa',type:'Commercial',stage:'Plans requested',score:79}]
const money=n=>new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:0}).format(n||0)
export default function Home(){
 const [tab,setTab]=useState('Overview');const [leads,setLeads]=useState(seedLeads);const [quotes,setQuotes]=useState([]);const [invoices,setInvoices]=useState([])
 const addQuote=()=>setQuotes(q=>[...q,{id:`Q-${String(q.length+1).padStart(4,'0')}`,customer:'New customer',project:'Untitled project',place:'Palawan',status:'Draft',items:[{product:'900 Series sliding',qty:1,width:2975,height:2700,unit:34304}],terms:'70% down payment'}])
 const approveQuote=i=>{const q=quotes[i];setQuotes(x=>x.map((v,n)=>n===i?{...v,status:'Approved'}:v));if(!invoices.some(v=>v.quote===q.id))setInvoices(x=>[...x,{id:`INV-${String(x.length+1).padStart(4,'0')}`,quote:q.id,customer:q.customer,project:q.project,total:q.items.reduce((s,a)=>s+a.qty*a.unit,0),paid:0,status:'Down payment due'}])}
 return <main><aside className="sidebar"><div className="brand"><div className="mark">A</div><div><strong>AZARRAGA</strong><span>COMMERCIAL AGENT</span></div></div><nav>{['Overview','Leads','Quotes','Invoices','Commercial Memory'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</nav><div className="agent"><BrainCircuit size={18}/><div><b>Commercial Memory</b><span>Operational</span></div></div></aside><section className="workspace"><header><div><p>AZARRAGA GLASS & ALUMINUM</p><h1>{tab}</h1></div><button className="primary" onClick={()=>{addQuote();setTab('Quotes')}}><Plus size={16}/> New Quote</button></header>
 {tab==='Overview'&&<Overview leads={leads} quotes={quotes} invoices={invoices} setTab={setTab}/>} {tab==='Leads'&&<Leads leads={leads} setLeads={setLeads}/>} {tab==='Quotes'&&<Quotes quotes={quotes} setQuotes={setQuotes} addQuote={addQuote} approveQuote={approveQuote}/>} {tab==='Invoices'&&<Invoices invoices={invoices} setInvoices={setInvoices}/>} {tab==='Commercial Memory'&&<Memory/>}</section></main>
}
function Overview({leads,quotes,invoices,setTab}){return <><div className="hero"><div><span className="eyebrow">COMMERCIAL OPERATIONS</span><h2>Find the customer. Quote the job. Get paid.</h2><p>One operating record from opportunity to plans, quotation, customer PO, down payment, delivery and final billing.</p></div><div className="territory"><MapPin/><b>Palawan</b><span>Puerto Princesa · El Nido · San Vicente</span></div></div><div className="metrics"><Metric label="Open leads" value={leads.length}/><Metric label="Quotes" value={quotes.length}/><Metric label="Outstanding invoices" value={money(invoices.reduce((s,x)=>s+x.total-x.paid,0))}/><Metric label="Memory products" value={products.length}/></div><h3>Commercial workflow</h3><div className="cards"><Action icon={<Search/>} title="Find business" text="Research and qualify Palawan construction opportunities." onClick={()=>setTab('Leads')}/><Action icon={<FileText/>} title="Win business" text="Plans and measurements become a controlled quote." onClick={()=>setTab('Quotes')}/><Action icon={<ReceiptText/>} title="Bill business" text="Approved quote data flows into billing once." onClick={()=>setTab('Invoices')}/></div></>}
function Leads({leads,setLeads}){return <><div className="sectionHero"><div><span className="eyebrow">LEAD AGENT</span><h2>Find work before competitors do.</h2><p>Target new resorts, hotels, villas, homes, renovations, restaurants and developments across Palawan. The conversion goal is simple: <b>Send us the plans.</b></p></div><button className="primary" onClick={()=>setLeads(x=>[...x,{name:'New opportunity',place:'Palawan',type:'Unqualified',stage:'Research',score:50}])}><Search size={16}/> Add research lead</button></div><div className="table"><div className="tr th"><span>Opportunity</span><span>Location</span><span>Type</span><span>Stage</span><span>Fit</span></div>{leads.map((l,i)=><div className="tr" key={i}><strong>{l.name}</strong><span>{l.place}</span><span>{l.type}</span><span className="pill">{l.stage}</span><b>{l.score}%</b></div>)}</div></>}
function Quotes({quotes,setQuotes,addQuote,approveQuote}){return <><div className="sectionHero"><div><span className="eyebrow">QUOTE AGENT + DETERMINISTIC ENGINE</span><h2>Plans in. Reviewable quotation out.</h2><p>The agent structures the takeoff. Arithmetic remains deterministic. Historical selling prices are evidence, never silently treated as current cost.</p></div><button className="primary" onClick={addQuote}><Plus size={16}/> New Quote</button></div>{quotes.length===0?<Empty icon={<Upload/>} title="Start with whatever you have" text="Architectural PDF, window/door schedule, measurements, photos or customer request." action="Create quote" onClick={addQuote}/>:quotes.map((q,i)=><QuoteEditor key={q.id} q={q} i={i} setQuotes={setQuotes} approveQuote={approveQuote}/>)}</>}
function QuoteEditor({q,i,setQuotes,approveQuote}){const total=useMemo(()=>q.items.reduce((s,x)=>s+x.qty*x.unit,0),[q]);const patch=(field,value)=>setQuotes(a=>a.map((x,n)=>n===i?{...x,[field]:value}:x));const item=q.items[0];const patchItem=(field,value)=>setQuotes(a=>a.map((x,n)=>n===i?{...x,items:[{...x.items[0],[field]:value}]}:x));return <div className="quote"><div className="quoteTop"><div><span>{q.id} · {q.status}</span><input value={q.customer} onChange={e=>patch('customer',e.target.value)}/><input value={q.project} onChange={e=>patch('project',e.target.value)}/></div><button className="outline"><Upload size={15}/> Upload plans / PO</button></div><div className="quoteGrid"><label>Product<select value={item.product} onChange={e=>patchItem('product',e.target.value)}>{products.map(p=><option key={p}>{p}</option>)}</select></label><label>Qty<input type="number" value={item.qty} onChange={e=>patchItem('qty',+e.target.value)}/></label><label>Width mm<input type="number" value={item.width} onChange={e=>patchItem('width',+e.target.value)}/></label><label>Height mm<input type="number" value={item.height} onChange={e=>patchItem('height',+e.target.value)}/></label><label>Unit price<input type="number" value={item.unit} onChange={e=>patchItem('unit',+e.target.value)}/></label></div><div className="calc"><Calculator/><span>Deterministic total</span><strong>{money(total)}</strong></div><div className="flow"><span>TAKEOFF</span><ArrowRight/><span>REVIEW</span><ArrowRight/><span>QUOTE</span><ArrowRight/><span>CUSTOMER PO</span></div>{q.status!=='Approved'&&<button className="primary" onClick={()=>approveQuote(i)}><CheckCircle2 size={16}/> Approve quote & create billing record</button>}</div>}
function Invoices({invoices,setInvoices}){return <><div className="sectionHero"><div><span className="eyebrow">BILLING WORKFLOW</span><h2>Enter the project once.</h2><p>Approved quote → customer PO → project → down payment → delivery/progress → final billing. Philippine tax-document compliance remains a separate verified boundary.</p></div></div>{invoices.length===0?<Empty icon={<ReceiptText/>} title="No billing records yet" text="Approve a quote and its commercial data will carry forward here without re-entry."/>:<div className="table invoices"><div className="tr th"><span>Invoice</span><span>Customer / project</span><span>Total</span><span>Paid</span><span>Status</span></div>{invoices.map((x,i)=><div className="tr" key={x.id}><strong>{x.id}<small>from {x.quote}</small></strong><span>{x.customer}<small>{x.project}</small></span><b>{money(x.total)}</b><span>{money(x.paid)}</span><button className="pill" onClick={()=>setInvoices(a=>a.map((v,n)=>n===i?{...v,paid:v.total*.7,status:'70% down payment recorded'}:v))}>{x.status}</button></div>)}</div>}</>}
function Memory(){return <><div className="sectionHero"><div><span className="eyebrow">COMMERCIAL MEMORY</span><h2>Business knowledge that improves with every job.</h2><p>Won quotes become pricing evidence. Invoices confirm actual business. Repeat customers and architects become relationship memory.</p></div></div><div className="memory"><div><h3>Product taxonomy</h3><p>Initial normalized Azarraga systems.</p></div><div className="tags">{products.map(p=><span key={p}>{p}</span>)}</div></div><div className="cards"><Action icon={<Building2/>} title="Historical evidence" text="Customer, project, date, location, quantity, unit price, discounts, delivery, installation and terms."/><Action icon={<Calculator/>} title="Pricing separation" text="Historical selling price ≠ current input cost ≠ approved current selling price."/><Action icon={<BrainCircuit/>} title="Memory loop" text="Every lead, quote outcome and invoice enriches the next commercial decision."/></div></>}
function Metric({label,value}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}function Action({icon,title,text,onClick}){return <div className="action" onClick={onClick}><div className="icon">{icon}</div><h3>{title}</h3><p>{text}</p>{onClick&&<button>Open workspace <ArrowRight size={14}/></button>}</div>}function Empty({icon,title,text,action,onClick}){return <div className="empty"><div className="icon">{icon}</div><h2>{title}</h2><p>{text}</p>{action&&<button className="primary" onClick={onClick}>{action}<ArrowRight size={15}/></button>}</div>}
