import memory from '../data/commercial-memory-2026.json'
import {id} from './commercial-store'
const records=memory.records||[]
const money=n=>Math.round((Number(n)||0)*100)/100
const text=v=>String(v||'').trim()
export function quoteTotals(items=[],logistics=0,discount=0){const normalized=items.map((x,i)=>{const qty=Number(x.qty||0),unitPrice=Number(x.unitPrice||0);return {...x,line:i+1,qty,unit:x.unit||'set',widthMm:Number(x.widthMm||0),heightMm:Number(x.heightMm||0),unitPrice,amount:money(qty*unitPrice)}});const subtotal=money(normalized.reduce((s,x)=>s+x.amount,0));return {items:normalized,subtotal,logistics:money(logistics),discount:money(discount),total:money(subtotal+Number(logistics||0)-Number(discount||0))}}
function evidencePrices(r){return r.observed_unit_prices_php||[r.unit_price_php].filter(Boolean)}
export function findEvidence(item){const product=text(item.product||item.description).toLowerCase(),glass=text(item.glass).toLowerCase(),frame=text(item.frame).toLowerCase();return records.map(r=>{const s=JSON.stringify(r).toLowerCase();let score=0;if(product&&s.includes(product))score+=6;product.split(/\s+/).filter(x=>x.length>3).forEach(x=>{if(s.includes(x))score++});if(glass&&s.includes(glass))score+=3;if(frame&&s.includes(frame))score+=2;return {r,score}}).filter(x=>x.score>0).sort((a,b)=>b.score-a.score).slice(0,5).map(({r,score})=>({document:r.document,date:r.date,customer:r.customer,project:r.project,category:r.category,glass:r.glass||'',observedUnitPricesPhp:evidencePrices(r),score,note:'Historical evidence only — never auto-applied as current price.'}))}
export function buildQuote(input={}){const calc=quoteTotals(input.items,input.logistics,input.discount),warnings=[];if(!text(input.customer))warnings.push('Customer is required');if(!text(input.project))warnings.push('Project is required');if(!calc.items.length)warnings.push('At least one line item is required');calc.items.forEach((x,i)=>{if(!text(x.description)&&!text(x.product))warnings.push(`Line ${i+1}: product/description required`);if(x.qty<=0)warnings.push(`Line ${i+1}: quantity must be greater than zero`);if(x.unitPrice<=0)warnings.push(`Line ${i+1}: current unit price requires owner entry/approval`)});return {id:input.id||id('Q'),status:warnings.length?'draft_needs_review':'draft_ready',customer:text(input.customer),project:text(input.project),location:text(input.location),date:input.date||new Date().toISOString().slice(0,10),terms:text(input.terms),leadTime:text(input.leadTime),notes:text(input.notes),...calc,evidence:calc.items.map(findEvidence),warnings,pricingRule:'Historical prices are evidence only. Current quote prices must be explicitly entered or approved by owner.'}}
